"""empty message

Revision ID: 9f034a826909
Revises: 
Create Date: 2021-01-25 10:06:56.801338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f034a826909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storingusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storingusers_email'), 'storingusers', ['email'], unique=True)
    op.create_index(op.f('ix_storingusers_username'), 'storingusers', ['username'], unique=True)
    op.create_table('todo_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['storingusers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_tasks_timestamp'), 'todo_tasks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_tasks_timestamp'), table_name='todo_tasks')
    op.drop_table('todo_tasks')
    op.drop_index(op.f('ix_storingusers_username'), table_name='storingusers')
    op.drop_index(op.f('ix_storingusers_email'), table_name='storingusers')
    op.drop_table('storingusers')
    # ### end Alembic commands ###
